### PR TITLE
translate the configuration file into English

### PR DESCRIPTION
**Pull request by alex19EP**
also add a link to configuration documentation.

### CODE REVIEW

**Comment by bmivzkrp** [comment]
I think that for Linux the configuration file should be in English.
Translated configuration files can be located in "PREFIX/share/doc".
In my opinion, the comments in the configuration file should be supplemented with the following information:

1. The minimum and maximum value of each parameter;

2. Similarly, but for "min_sonic_rate" (users often ask what is the maximum value of this parameter).

This configuration file will be especially useful for beginners. It will be easier for a beginner to copy the configuration file translated into his native language and edit it than to read the Wiki. Beginners are often afraid to do something wrong, so this file should be part of RHVoice.

**Comment by Olga-Yakovleva** [comment]
Ok, so we have conflicting goals here: keep the files with the comments 
in both languages for beginners, don't assume which language the user 
prefers, but at the same time avoid complicating the implementation by 
multiple versions of the file in the same directory. I can think of only 
one compromize: create an initial common file only with brief comments 
in both languages. The comments will include both the links to the 
corresponding documentation and the links to the examples with detailed 
comments, telling the user to replace this file with the downloaded one 
or use that file as a guide on how to edit the settings. Will that do?

**Comment by zstanecic** [comment]
yep that will do

**Comment by beqabeqa473** [comment]
yes, great decision

On 8/24/20, zstanecic <notifications@github.com> wrote:
> yep that will do
>
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/pull/164#issuecomment-679139604


-- 
with best regards beqa

**Comment by bmivzkrp** [comment]
24.08.20 16:43, Olga Yakovleva wrote:
> Ok, so we have conflicting goals here:

Just in case, I will explain in detail what I mean.
We create a catalog

Prefix/share/doc/RHVoice/

In this directory we create subdirectories corresponding to the supported languages (UK, EN, and the like).
In these subdirectories we place the translated documentation, including an example of a configuration file.
In my opinion, you should follow the generally accepted rules, leaving the system configuration file in English. If the user needs a configuration file with translated comments, he will copy it and replace the system configuration file.
Note: if in the future we have not only a global configuration file but also a local one (ie separate for each user), then such a file can be installed in the user s home directory according to his language.

All of the above applies to Linux only.

**Pull request merged**
