### PR TITLE
Android build system update

### PR DESCRIPTION
**Pull request by beqabeqa473**
Updated android gradle plugin to 3.6.0.
added a new myNdkVersion variable to set specific ndk version (Needed by new android plugin).
updated dependencies to latest versions
updated compile and target sdk versions to 29 (android 10) & buildTools to 29.0.3
added gradle.properties to set variables for androidx support (Needed by newer android plugin versions)
updated .gitignore

### CODE REVIEW

**Comment by Olga-Yakovleva** [comment]
Should we set a specific ndk version? If I understand the docs 
correctly, the android.ndkVersion property should only be used to 
override the default selection,, which is the newest of all the 
installed versions. Just like android.buildToolsVersion, which I 
shouldn't actually be setting in the script, as the default selection 
should be fine.

**Comment by beqabeqa473** [comment]
i've tried to leave ndk version value by default, but then gradle
complainned that version older that sdk manager installed is not
found, so i added ndkVersion after that.

On 3/5/20, Olga-Yakovleva <notifications@github.com> wrote:
> Should we set a specific ndk version? If I understand the docs
> correctly, the android.ndkVersion property should only be used to
> override the default selection,, which is the newest of all the
> installed versions. Just like android.buildToolsVersion, which I
> shouldn't actually be setting in the script, as the default selection
> should be fine.
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/pull/130#issuecomment-595282439


-- 
with best regards beqa

**Comment by Olga-Yakovleva** [comment]
Yes, I can reproduce the problem. This looks like a bug in the Android 
Gradle plugin 3.6.0. Perhaps there will be a minor update with a fix in 
the near future. I don't want to switch to 3.6 until then. There is no 
special reason to do it, and we can just switch to 3.5.3 for now.

**Comment by beqabeqa473** [comment]
ok, i will downgrade gradle plugin to 3.5.3

it seems this can be also fixed by setting ANDROID_NDK_HOME
environment variable to ndk path, but this is also something that
doesn't work out of the box.



On 3/5/20, Olga-Yakovleva <notifications@github.com> wrote:
> Yes, I can reproduce the problem. This looks like a bug in the Android
> Gradle plugin 3.6.0. Perhaps there will be a minor update with a fix in
> the near future. I don't want to switch to 3.6 until then. There is no
> special reason to do it, and we can just switch to 3.5.3 for now.
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/pull/130#issuecomment-595336555


-- 
with best regards beqa

**Pull request merged**
