### PR TITLE
Scons fixes

### LINKED ISSUE #170: Compilation with SCons is broken
I should have tested before merging pr #135. I am aware of the problems and will deal with them.

### PR DESCRIPTION
**Pull request by KOLANICH**
Fixes #170

### CODE REVIEW

**Comment by smok105** [comment]
I'm a new user, tell me the changes have already been made and can I try through scons?

**Comment by zvezdochiot** [comment]
Hi @KOLANICH .

```sh
scons
...
TypeError: 'encoding' is an invalid keyword argument for this function:
  File "/home/smu8uch4/WORK/soft/src/t/RHVoice/SConstruct", line 359:
    build_for_linux(base_env,vars)
  File "/home/smu8uch4/WORK/soft/src/t/RHVoice/SConstruct", line 313:
    build_binaries(base_env,user_vars)
  File "/home/smu8uch4/WORK/soft/src/t/RHVoice/SConstruct", line 310:
    duplicate=0)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 609:
    return method(*args, **kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 546:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 260:
    exec _file_ in call_stack[-1].globals
  File "/home/smu8uch4/WORK/soft/src/t/RHVoice/src/core/SConscript", line 56:
    processConfig(Dir(".").srcnode().abspath + "/config.h.in", Dir(".").srcnode().abspath + "/config.h", coreConfig)
  File "/home/smu8uch4/WORK/soft/src/t/RHVoice/src/core/SConscript", line 46:
    with open(inFName, "rt", encoding = "utf-8") as f:
```

**Comment by KOLANICH** [comment]
Python 2 is EOL.

**Comment by smok105** [comment]
Good day! this error knocks out

**Comment by smok105** [comment]
Good day! this error knocks out
```
$ scons
scons: Reading SConscript files ...
Mkdir("build/linux")
Checking whether the C compiler works... yes
Checking whether the C++ compiler works... yes
Checking for pkg-config... yes
Checking for libpulse-simple... yes
Checking for ao... yes
Checking for portaudio-2.0... no
Checking Speech Dispatcher version ... no
TypeError: File /home/dmytro/work/apiservice/RHVoice/data/languages/CMakeLists.txt found where directory expected.:
  File "/home/dmytro/work/apiservice/RHVoice/SConstruct", line 360:
    build_for_linux(base_env,vars)
  File "/home/dmytro/work/apiservice/RHVoice/SConstruct", line 316:
    SConscript(os.path.join(subdir,"SConscript"),exports={"env":base_env},
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 660:
    return method(*args, **kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 286:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/home/dmytro/work/apiservice/RHVoice/data/SConscript", line 38:
    subdir=dir.Dir(subdir_name)
  File "/usr/lib/scons/SCons/Node/FS.py", line 1643:
    return self.fs.Dir(name, self, create)
  File "/usr/lib/scons/SCons/Node/FS.py", line 1394:
    return self._lookup(name, directory, Dir, create)
  File "/usr/lib/scons/SCons/Node/FS.py", line 1361:
    return root._lookup_abs(p, fsclass, create)
  File "/usr/lib/scons/SCons/Node/FS.py", line 2398:
    result.diskcheck_match()
  File "/usr/lib/scons/SCons/Node/FS.py", line 1606:
    diskcheck_match(self, self.isfile,
  File "/usr/lib/scons/SCons/Node/FS.py", line 393:
    return self.func(*args, **kw)
  File "/usr/lib/scons/SCons/Node/FS.py", line 414:
    raise TypeError(errorfmt % node.get_abspath())
```

**Comment by smok105** [comment]
what am I doing wrong

**Comment by zvezdochiot** [comment]
Hi @smok105 .

Where are you from and how did you clone? Throw the cloning team here.

PS: I cloned like this:
```sh
git clone https://github.com/KOLANICH/RHVoice -b scons_fix
```

**Comment by KOLANICH** [comment]
Are you using the latest pushed version? I remember I have fixed this error.

**Comment by Olga-Yakovleva** [comment]
OK, sorry for duplicating the work, but I pushed my own fixes.

**Comment by zvezdochiot** [comment]
Привет @Olga-Yakovleva

https://github.com/Olga-Yakovleva/RHVoice/commit/653f443ebaac54e6b663a7a5c20daa53e78aeb91 in Debian Wheezy runs. You can close this PR.

**Comment by KOLANICH** [comment]
I feel like my fix is of better quality.

**Comment by zvezdochiot** [comment]
Hi @KOLANISH .

Maybe better quality. Then finish everything. Not all at once.

**Comment by Olga-Yakovleva** [comment]
I wanted a quick fix to make the code compilable again. If you don't 
mind reworking your code in src/core/SConscript to make it a proper 
builder for SCons, I'll be glad to merge it. Right now it is writing an 
output file at the first stage, instead of at the second (build) stage.

**Comment by smok105** [comment]
> Привет @ smok105 .
> 
> Откуда вы и как клонировали? Бросьте сюда команду клонирования.
> 
> PS: Я клонировал вот так:
> 
> ```shell
> git clone https://github.com/KOLANICH/RHVoice -b scons_fix
> ```


that's cool! It works! thank

**Comment by KOLANICH** [comment]
Utilized scons Textfile for that. Now it doesn't generate them on `--help`.

**Pull request merged**
