### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
To get https://gitlab.com/fdroid/rfp/-/issues/1255 going, which is stalled because of missing Fastlane for 3 months already. Once this is merged and covered by a tag, that RFP could finally be processed. Be welcome to complement this basic "starter set" – for example by screenshots and per-release changelogs. Find [my Fastlane cheat-sheet](https://gitlab.com/snippets/1895688) at your service if you need a quick guide :smiley:

### CODE REVIEW

**Comment by IzzySoft** [comment]
Thanks a lot, @alex19EP – the MR at F-Droid was now just processed by @licaon-kter :smiley:

**Comment by alex19EP** [comment]
ok. could you ping me when it becomes available in F-Droid - will close issue at our end.

**Comment by IzzySoft** [comment]
Uh, I'll try to remember – I just don't delete the notification I just got for this PR to keep a reminder :smile: If all works well, it shouldn't be much more than a week now. Should you meanwhile make a new release (where the tag then would cover the fastlane structures), please drop a note here as well so I can cross-check on our end. Thanks again!

**Comment by ildar** [comment]
Landed

**Comment by IzzySoft** [comment]
Yes, I just noticed. And fastlane was pulled fine, yay! Playing at Mares' slogan ("Just add water") – just add screenshots :rofl:

**Pull request merged**
