### PR TITLE
Add CI with AppVeyor

### PR DESCRIPTION
**Pull request by abitrolly**
If you enable AppVeyor at https://www.appveyor.com/ you will get automatic testing for `scons` PR on Windows, preventing errors like this https://github.com/Olga-Yakovleva/RHVoice/pull/217#issuecomment-723649210

### CODE REVIEW

**Comment by abitrolly** [comment]
AppVeyor provides sane jump to build logs, unlike GitHub Actions.

**Comment by alex19EP** [comment]
i want to use github actions for ci/cd. I don't like to depend on other services.

**Comment by abitrolly** [comment]
GitHub Actions is another service, which needs maintenance and support. The key difference is login and repo permissions.

**Comment by abitrolly** [comment]
Here is the example output. You can setup GitHub actions and choose the one which works better.

https://ci.appveyor.com/project/yakshaveinc/rhvoice

**Comment by beqabeqa473** [comment]
i've submitted a pr with github actions in place earlier.

On 11/9/20, Anatoli Babenia <notifications@github.com> wrote:
> Here is the example output. You can setup GitHub actions and choose the one
> which works better.
>
> https://ci.appveyor.com/project/yakshaveinc/rhvoice
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/pull/230#issuecomment-723962651


-- 
with best regards beqa

**Comment by alex19EP** [comment]
> i've submitted a pr with github actions in place earlier.

yes. I've seen that. but it only for android. and IMO it's not very helpful. also I think this should be done when we move into the rhvoice organization. I hope it will happen soon.

**Comment by abitrolly** [comment]
@alex19EP I will be adding fixes to my branch. Feel free to reopen or pull any time.

**Pull request closed without merging**
