### PR TITLE
Added sanitizers support

### PR DESCRIPTION
**Pull request by KOLANICH**
Just adds options to build with sanitizers enabled.

### CODE REVIEW

**Comment by alex19EP** [comment]
pleas fill the description.

**Comment by zstanecic** [comment]
Hi to all,

The sanitizers submodule cannot be initialized. 

To reproduce this, please do 

$ git submodule niit

$ git submodule update

After the second command, I git an error.

**Comment by KOLANICH** [comment]
You are right, [the URI in .gitmodules is wrong](https://github.com/Olga-Yakovleva/RHVoice/pull/176/files#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584R3)

**Comment by alex19EP** [comment]
> 
> 
> You are right, [the URI in .gitmodules is wrong](https://github.com/Olga-Yakovleva/RHVoice/pull/176/files#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584R3)

hm. yep. i see. i think it should be https://github.com/arsenm/sanitizers-cmake.git

**Comment by KOLANICH** [comment]
https://github.com/Olga-Yakovleva/RHVoice/pull/228

**Pull request merged**
