### PR TITLE
Implemented CMake building for Linux components

### PR DESCRIPTION
**Pull request by KOLANICH**
Translated the scons build-scripts to CMake.
Added support of compiler-based mitigations against various attacks (DEP, ASLR, Spectre resistance) via my CMake script .
Implemented creation of packages (for Debian, for RPM-based distros I haven't tested) for components suitable for Linux-based OSes.
Added sample rate parameter to RHVoice-test (though it doesn't really work).
Added 96k to the list of sample rates (though it turned out that even 48k is not supported).

What DOES NOT WORK:
* RHVoice built without MAGE crashes IDK why
* building SAPI5 and NVDA modules is not yet implemented.
* **UNDEFINED BEHAVIOR HAS BEEN DETECTED IN THE SOURCE** Probably a use-before-init vulnr. When compiled with CLang (11, latest from the official apt) this shit sigsegvs. When compiled with g++ 9 it works. I guess this shit must be rewritten to rust. https://github.com/jameysharp/corrode may be helpful. At least you should hardcorely valgrind, ASan and UBSan it.

Closes: #151
Closes: #88

### CODE REVIEW

**Comment by zvezdochiot** [comment]
History:
* prehistory: #126 
* problem of MAGE: #133

**Comment by dmikushin** [comment]
Hi @KOLANICH @zvezdochiot Excellent patch. I've narrowed this down with some fixes into https://github.com/dmikushin/RHVoice/commit/7d954bb320353ea10409160ccdd550c1aab45e92 and https://github.com/dmikushin/RHVoice/commit/4f74ac91c4e968f78a15af066df6aff62cf967a3 and https://github.com/dmikushin/RHVoice/commit/56c8b8b88ee7805f81d58b64db4a627e1a9f5990

I'm using MacOS X Catalina and Portaudio backend. Would be really great to test Ubuntu configurations as well.

**Comment by beqabeqa473** [comment]
hi all.

i don't see an advantage of cmake over scons.
first of all, scons is easier to install, as python for most of us is
language of daily bases.

what you can say as an argument in favour of changing scons to cmake?

On 5/28/20, Dmitry Mikushin <notifications@github.com> wrote:
> Hi @KOLANICH @zvezdochiot Excellent patch. I've narrowed this down with some
> fixes into
> https://github.com/dmikushin/RHVoice/commit/7d954bb320353ea10409160ccdd550c1aab45e92
> and
> https://github.com/dmikushin/RHVoice/commit/4f74ac91c4e968f78a15af066df6aff62cf967a3
> and
> https://github.com/dmikushin/RHVoice/commit/56c8b8b88ee7805f81d58b64db4a627e1a9f5990
>
> I'm using MacOS X Catalina and Portaudio backend. Would be really great to
> test Ubuntu configurations as well.
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/pull/135#issuecomment-634966692


-- 
with best regards beqa

**Comment by zvezdochiot** [comment]
Hi @beqabeqa473 .

https://github.com/Olga-Yakovleva/RHVoice/pull/135#commitcomment-39218349 . See "PS".

**Comment by beqabeqa473** [comment]
sorry, but not an argument for most of us

On 5/28/20, звездочёт <notifications@github.com> wrote:
> Hi @beqabeqa473 .
>
> https://github.com/Olga-Yakovleva/RHVoice/pull/135#commitcomment-39218349 .
> See "PS".
>
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/pull/135#issuecomment-635071027


-- 
with best regards beqa

**Comment by zvezdochiot** [comment]
Hi @beqabeqa473 .

:warning: Not an argument for you, but an argument for me.

**Comment by dmikushin** [comment]
Dear @beqabeqa473 I really appreciate your great work and fully understand your argument in favor of Scons. I've been using SCons myself some time ago. CMake is de facto standard build system these days. I guess what I like in CMake most of all is modularity. In opensource, we often need to integrate several codebases or libraries into one product (like Mage is integrated into RHVoice, for example). If all components are already in CMake, this can be done just instantly.

**Comment by beqabeqa473** [comment]
hello.
first of all, i am not more than usual user of this product in this
term and am expressing my opinion.
about scons, it is much easier to install scons with pip for example
rather than cmake, moreover, this doesn't affect runtime execution.
really, i can't find an argument in favour of changing build system.
everything is working in scons, if there are some limitations, which
are possible in cmake but not in scons, ok, but i can't think off
anything about that.

On 5/28/20, Dmitry Mikushin <notifications@github.com> wrote:
> Dear @beqabeqa473 I really appreciate your great work and fully understand
> your argument in favor of Scons. I've been using SCons myself some time ago.
> CMake is de facto standard build system these days. I guess what I like in
> CMake most of all is modularity. In opensource, we often need to integrate
> several codebases or libraries into one product (like Mage is integrated
> into RHVoice, for example). If all components are already in CMake, this can
> be done just instantly.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/pull/135#issuecomment-635208950


-- 
with best regards beqa

**Comment by alex19EP** [comment]
> Fixed the bugs preventing building with clang 11 by updating a file from RapidXML from https://raw.githubusercontent.com/johelegp/RapidXml/master/rapidxml_iterators.hpp and some other minor code fixes.

it will be good if you put it in a separate commit.
Now it’s quite difficult to revue this PR since everything is in one commit.

**Comment by dmikushin** [comment]
@alex19EP FWIW https://github.com/dmikushin/RHVoice/commit/56c8b8b88ee7805f81d58b64db4a627e1a9f5990

**Comment by alex19EP** [comment]
> 
> 
> @alex19EP FWIW [dmikushin@56c8b8b](https://github.com/dmikushin/RHVoice/commit/56c8b8b88ee7805f81d58b64db4a627e1a9f5990)

ok nice. 😊 it will be great if you send PR.

**Comment by KOLANICH** [comment]
>Now it’s quite difficult to revue this PR since everything is in one commit.

Otherwise it may  be quite difficult for me to rebase over upstream. I can split into separate commits and even separate branches, but it makes sense only if these separate commits and branches are immediately merged, not ignored for months.

**Comment by alex19EP** [comment]
yep I understand. I just want to fix this situation. 😊

> but it makes sense only if these separate commits and branches are immediately merged, not ignored for months.

I can’t speak for @Olga-Yakovleva but I will do my best. 🖐

**Comment by dmikushin** [comment]
Dear @alex19EP, please see the PR series. One high-priority fix https://github.com/dmikushin/RHVoice/commit/48f65efc9a2b22cb2a396355d8ff7d86144d1021 is yet to go, once these are accepted.

**Comment by KOLANICH** [comment]
@alex19EP @Olga-Yakovleva

**Comment by KOLANICH** [comment]
@Olga-Yakovleva, ping

**Comment by beqabeqa473** [comment]
of course, it is @Olga-Yakovleva's decision what to do with this pr, but i'll ask once again.
what advantages are provided with cmake implementation over current scons implementation?
what happens when thing comes to building windows components such as nvda addon and sapi part with corresponding installers?

do you really think that without these parts it has reason to be merged?

most of distroes have python preinstalled and it is very simple to install scons. why we should install one more build system?
i'll repeat my question, what advantages it has over scons implementation?

**Comment by KOLANICH** [comment]
>what advantages are provided with cmake implementation over current scons implementation?

Again:
* it has a compiler abstraction layer.
* it has dependency discovery framework and a bunch of libs for it
* it has CPack, which is needed for packaging.
* it supports ninja lower level build system
* and the most importantly, it doesn't depend on python. On Windows NOONE wants python in order to build software. In the past, before I started to use python myself, if a lib used python for building, my algo for it was simple: either I use prebuilt lib, or I rewrite the build system into CMake, or I look for a replacement with less shitty build system. Noone wants to install large shit he doesn't use personally. I use this algo for Bazel currently, which is one of the worst build systems in the world, that meets only the needs of the enterprises like Google.

>what happens when thing comes to building windows components such as nvda addon and sapi part with corresponding installers?

CPack supports NSIS and can make installers for Windows.

>do you really think that without these parts it has reason to be merged?

I haven't deteted the scons scripts. So ones needing them still can use scons to build them. I think someone actually using Windows and NVDA should help with porting these parts to CMake, so we can get rid of scons fully.

**Comment by beqabeqa473** [comment]
i don't think it was a problem for most of people to install python.
as a software developer, if i am making something quick and simple,
first language what comes to my mind is python.

as for compiler, when compiling binaries, everything comes down to
gcc/g++ on linux and corresponding compilers for windows.

what is the reason changing thing which is working, and it is working
quite well, if someone don't want to install python.
i can also say that i don't want to install cmake on my system, but
anyway i have cmake for projects which needs it for building.

On 8/1/20, KOLANICH <notifications@github.com> wrote:
>>what advantages are provided with cmake implementation over current scons
>> implementation?
>
> Again:
> * it has a compiler abstraction layer.
> * it has dependency discovery framework and a bunch of libs for it
> * it has CPack, which is needed for packaging.
> * it supports ninja lower level build system
> * and the most importantly, it doesn't depend on python. On Windows NOONE
> wants python in order to build software. In the past, before I started to
> use python myself, if a lib used python for building, my algo for it was
> simple: either I use prebuilt lib, or I rewrite the build system into CMake,
> or I look for a replacement with less shitty build system. Noone wants to
> install large shit he doesn't use personally. I use this algo for Bazel
> currently, which is one of the worst build systems in the world, that meets
> only the needs of the enterprises like Google.
>
>>what happens when thing comes to building windows components such as nvda
>> addon and sapi part with corresponding installers?
>
> CPack supports NSIS and can make installers for Windows.
>
>>do you really think that without these parts it has reason to be merged?
>
> I haven't deteted the scons scripts. So ones needing them still can use
> scons to build them. I think someone actually using Windows and NVDA should
> help with porting these parts to CMake, so we can get rid of scons fully.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/pull/135#issuecomment-667550339


-- 
with best regards beqa

**Comment by dmikushin** [comment]
> what is the reason changing thing which is working

We all have different views and preferences. There are often multiple "quite good" ways to do the same thing. Offering multiple different options is an advantage, not a drawback. Think of following: why not to grant CMake alongside with SCons, if it potentially may allow more people to enjoy RHVoice?

**Comment by Olga-Yakovleva** [comment]
All,

Sorry, but I'm not familiar with cmake at all, so before I merge this, a 
probably very basic question: which command do I use to list the 
available configuration variables (that is, what is the equivalent of 
something like "../configure --help")?

SCons stays in any case, just because I like it. And the whole reason 
why I like it is because it not only uses an actual proper full 
programming language, but a very popular modern scripting language at 
that, so all kinds of third-party libraries are available. The next 
implementation of the voice building system in RHVoice will actually be 
using SCons. Besides, this is the system I know. So, it will be two 
options, whichever the user prefers. I will still implement possible 
updates in SCons myself, and the community will be maintaining the cmake 
variant.

**Comment by zvezdochiot** [comment]
Привет @Olga-Yakovleva .

Для конфигурации имеется ncurses ui, запускается командой:
```sh
ccmake .
```
А если известны используемые переменные, можно передавать их значение непосредственно с помощью опции `-D`:
```sh
cmake -DYouOption=YouValue .
```

**Comment by Olga-Yakovleva** [comment]
Is this warning important?

CMake Warning (dev) at cmake/Hardening.cmake:82:

    Syntax Warning in cmake code at column 36


    Argument not separated from preceding token by whitespace.

  Call Stack (most recent call first):

    CMakeLists.txt:24 (include)

  This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by KOLANICH** [comment]
>Is this warning important?

I have pushed a fix.

>the whole reason why I like it is because it not only uses an actual proper full programming language,

Yeah, a good programming language is important, but having a toolkit of the basic stuff is much more important. We love python for its packages, but it lacks a proper package for high-level building of software, and meson is not a a solution, it is too low level. Scons is especially terrible, it has much more terrible UX and demands less structure than meson.

Contrary, CMake, though lacks most of the needed stuff to be a proper programming language, has a toolkit and is a framework rather than "write your script ae you want", so most the cmake building scripts have the same structure, the same cli args configuring some aspects and react predictably on them. This rigidity is used when CMake is integrated into metabuild systems (I am developing one).

and, as I said, python is to heavy for self-building on Windows. Noone wants to install it only to build RHVoice, if he doesn't apready have it because of other reasons.

I also perceive scons as slow. CMake utilizes ninja, which detects which object files have to be rebuilt and which are not. This makes rebuilds faster.

>which command do I use to list the available configuration variables (that is, what is the equivalent of something like "../configure --help")?

On the first invocation it generates a config file `CMakeCache.txt` that can be edited with any text editor. It contains "cache variables" (some of which are mapped to GUI switches and other prefs intended to be configured by users) and their metainfo, such as docstrings and "types" (in CMake there is only 1 type, which is a string, but types of cache variables just show to which GUI widgets they are mapped).

**Comment by dmikushin** [comment]
@KOLANICH Our target is to get CMake build system into the RHVoice. This target has no objections, given that SCons build system is kept as well for those who prefer it. That's a reasonable compromise at this point. Thus, we should stop any arguing against SCons, as it's not helpful. The decision is rather all about the quality of CMake script, which has been drastically improved thanks to your efforts.

**Comment by Olga-Yakovleva** [comment]
@KOLANICH Could you make the definitions in your config.h conditional to 
avoid conflicting with SCons? Something like "#ifdef USING_CMAKE...".

**Comment by smok105** [comment]
scons doesn't work now?

**Comment by KOLANICH** [comment]
This PR contains changes to C++ code requiring config to be generated, which is not present in scons. I have sent [a PR](#171) adding generation of the needed config into scons-based build scripts.

**Comment by andrewshadura** [comment]
To be completely fair, as I mentioned in another issue, this pull request shouldn’t have been merged: SCons is good enough, the upstream prefers it, and now they have to support both while benefits are very small.

CPack is useless for any distribution packages since they won’t accept it and will require their own native packaging anyway.

**Comment by dmikushin** [comment]
@andrewshadura Nobody is forced to use CMake. Why do you think someone has to support both systems?

**Comment by andrewshadura** [comment]
Because code nobody supports bitrots. The upstream would have to keep CMake files up to date when they make changes to the project.

**Pull request merged**
